### ISSUE TITLE
ssh-add prompt for ssh key passphrase 

### ISSUE THREAD

**Issue by abdulsalamalmahdi** [asifmahmud/ansible-git-clone#5]
would not it be useless that ansible woud promt user to insert ssh key passphrase even if once .

```yml
 - name: Add SSH key to SSH agent
   shell: |
       eval $(ssh-agent -s)
       ssh-add {{ KEY_PATH }}

```
would not the using the uri better for automation `git clone https://username:password@github.com/username/repository.git`
